Prezi Step 9: Calling the Anagrams Service
1. Update ChangeLetters action to issue command to getAllAnagrams

          ChangeLetters input ->
              if String.length input < 3 then
                  ( { model | letters = String.toLower input, words = [] }, Cmd.none )

              else if String.length input < 10 then
                  ( { model | letters = String.toLower input }, getAllAnagrams input )

              else
                  ( model, Cmd.none )

Error: no function `getAllAnagrams`

2. Implement getAllAnagrams
    a. Build request w/ URL and JSON decoder
    b. Build call w/ Callback Msg and Request

    Decoder |> Request |> Call

          getAllAnagrams : String -> Cmd Msg
          getAllAnagrams letters =
              anagramsDecoder
                  |> Http.get ("http://localhost:3000/anagrams/all-words-for/" ++ letters)
                  |> Http.send NewWords

Errors:
  - Missing anagramsDecoder
  - NewWords msg not hadled by update funcion

3. Implement Decoder function
  - import JSON parsing module
  - Map return values (JSON Array of Strings to Elm List of Strings)

            import Json.Decode as Decode exposing (Decoder, field)

            anagramsDecoder : Decoder (List String)
            anagramsDecoder =
              field "anagrams" (Decode.list Decode.string)

Remaining Error:
  - NewWords msg not hadled by update funcion

4. Implement NewWords action
  - Add NewWords to Msg type def
  - Handle NewWords case in update function
    - Return type => (Ok results) or (Err error)

              NewWords (Ok anagrams) ->
                  ( { model | words = anagrams }, Cmd.none )

              NewWords (Err error) ->
                  ( { model | words = [ Debug.toString error ] }, Cmd.none )